version: '3.9'

services:
  controller:
    image: ngrinder/controller:3.5.8
    ports:
      - "8088:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./controller:/opt/ngrinder-controller
  agent:
    image: ngrinder/agent:3.5.8
    restart: always
    links:
      - controller