version: '3.9'

services:
  controller:
    image: ngrinder/controller:3.5.8
    restart: always
    container_name: controller
    ports:
      - "8088:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./controller:/opt/ngrinder-controller

  agent-1:
    image: ngrinder/agent:3.5.8
    restart: always
    container_name: agent-1
    links:
      - controller:controller
    command: ["controller:8088"]
