version: '3.9'

services:
  locust:
    image: locustio/locust:2.16.1
    ports:
      - "8089:8089"
    environment:
      - LOCUST_HOST=http://host.docker.internal:8080 # localhost == host.docker.internal (localhost of docker host)
    volumes:
      - ../.:/locust
    command: -f /locust/locustfiles --class-picker