version: '3.9'

services:
  locust:
    image: locustio/locust:2.16.1
    ports:
      - "8089:8089"
    environment:
      - LOCUST_HOST=${LOCUST_HOST}
    volumes:
      - ../:/locust
    command: -f /locust/tests --class-picker